AWSTemplateFormatVersion: 2010-09-09
Description: support-sonarqube
Parameters:
  VpcId:
    Type: String
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    Default: vpc-e6e00183
  Subnets:
    Type: CommaDelimitedList
    Description: The list of SubnetIds in your Virtual Private Cloud (VPC)
    Default: subnet-cb91ae8d, subnet-a7b74ac2, subnet-179e8063
  Stack:
    Description: Applied directly as a tag
    Type: String
    Default: support
  Stage:
    Description: Applied directly as a tag
    Type: String
    Default: CODE
  App:
    Description: Applied directly as a tag
    Type: String
    Default: sonarqube
  AMI:
    Description: AMI ID (may be replaced by RiffRaff for latest baked AMI)
    Type: String
    Default: ami-05ccc315ac2233440
  OfficeCIDR:
    Description: Office IP range
    Type: String
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open up SSH access and enable HTTP access on the configured port
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref OfficeCIDR
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: !Ref OfficeCIDR
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  
  SonarQubeEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # Affinity: String
      AvailabilityZone: !GetAZs
      # BlockDeviceMappings: 
      #   - EC2 Block Device Mapping
      # CreditSpecification: CreditSpecification
      # DisableApiTermination: Boolean
      EbsOptimized: true
      # ElasticGpuSpecifications: [ ElasticGpuSpecification, ... ]
      # ElasticInferenceAccelerators: 
      #   - ElasticInferenceAccelerator
      # HostId: String
      # IamInstanceProfile: String
      ImageId: !Ref AMI
      # InstanceInitiatedShutdownBehavior: String
      InstanceType: t3.small
      # Ipv6AddressCount: Integer
      # Ipv6Addresses:
      #   - IPv6 Address Type
      # KernelId: String
      KeyName: thalia-sonarqube-CODE
      # LaunchTemplate: LaunchTemplateSpecification
      # LicenseSpecifications: 
      #   - LicenseSpecification
      # Monitoring: Boolean
      # NetworkInterfaces: 
      #   - EC2 Network Interface
      # PlacementGroupName: String
      # PrivateIpAddress: String
      # RamdiskId: String
      # SecurityGroupIds: 
      #   - String        
      SecurityGroups: 
          - !Ref InstanceSecurityGroup
      # SourceDestCheck: Boolean
      # SsmAssociations: 
      #   - SSMAssociation
      SubnetId: !Ref Subnets
      Tags: 
        - Key: Stack
          Value: !Ref Stack
          PropagateAtLaunch: true
        - Key: App
          Value: !Ref App
          PropagateAtLaunch: true
        - Key: Stage
          Value: !Ref Stage
          PropagateAtLaunch: true
      Tenancy: default
      # UserData: String
      # Volumes: 
      #   - EC2 MountPoint
      # AdditionalInfo: String